spring:
  h2:
    console.enabled: true
    console.path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 1
      connectionTimeout: 1000
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true